### ISSUE TITLE
Unable to place FOB after clearing enemy zones

### ISSUE THREAD

**Issue by Hunts2310** [DUWS-R-Team/DUWS-R#135]
Hi guys

Since the 0.5.0 update came down my friends and I have been unable to place down FOBs after clearing the enemy zones. We've scoured the zones clean of hostiles each time, had multiple friendly units in the zone alongside us and have tried saving and reloading the game several times to see if it simply was having issues updating but still nothing works. The option to place a FOB doesn't even appear in the support communication menu anymore despite having captured and cleared the zone.

**Comment by ultranoobian** [comment]
Hey Hunts2310,

I'm looking at the issue right now, just need a bit more info.

Does it always happen, Like even after restarting this mission?

And more importantly, Does it happen in multiplayer (Dedicated or Player-hosted, please specify)?

**Comment by ultranoobian** [comment]
Traced issue back to the server init file.

https://github.com/DUWS-R-Team/DUWS-R/blob/a61f7f5f153709c2a7152eee0afa3237461a211a/source/serverinit.sqf#L230

**Comment by ultranoobian** [comment]
Traced issue back to the server init file.

https://github.com/DUWS-R-Team/DUWS-R/blob/a61f7f5f153709c2a7152eee0afa3237461a211a/source/serverinit.sqf#L230

Initialization on server will result in executing on server and not players.

**Comment by Hunts2310** [comment]
Hey Ultra

The issue occurs every time we play. We've restarted the mission multiple times and it still pops up.
It happens in both multiplayer and single-player games. 
The ones we've set up have been player hosted so I don't know if it will occur in a dedicated server.

Hope that info helps. We're all really looking forward to getting back into the game. You guys have done a great job with the mod so far

**Comment by ultranoobian** [comment]
Thanks for the quick reply, I'll try to get this fixed asap.

**Comment by ultranoobian** [comment]
On further investigation, serverinit.sqf does not make ever pass:

https://github.com/DUWS-R-Team/DUWS-R/blob/a61f7f5f153709c2a7152eee0afa3237461a211a/source/serverinit.sqf#L209

**Comment by ultranoobian** [comment]
Issue has been fixed and deployed with #137

**Comment by ultranoobian** [comment]
Lully Lew 18 Apr @ 11:28pm  

> @SnowbiWan It pretty much works on a dedicated server for the most part. The only thing that fails at the moment is the ability to put a FOB down. The option doesn't appear. For the moment send a couple of squads into a captured area to keep hold of it. Although this negates teleportation if you wish to use it.

**Comment by Zerqz** [comment]
With the current steam version, I'm still having this issue. 

Do you recommend pulling the git repo and playing with that instead of the steam version if it isn't updated as frequently?
